// lib/type-colors.ts
export const typeColors: Record<string, string> = {
    normal: 'bg-gray-400 text-gray-800',
    fire: 'bg-red-500 text-white',
    water: 'bg-blue-500 text-white',
    electric: 'bg-yellow-400 text-gray-800',
    grass: 'bg-green-500 text-white',
    ice: 'bg-cyan-300 text-gray-800',
    fighting: 'bg-red-700 text-white',
    poison: 'bg-purple-500 text-white',
    ground: 'bg-amber-600 text-white',
    flying: 'bg-indigo-300 text-gray-800',
    psychic: 'bg-pink-500 text-white',
    bug: 'bg-lime-500 text-white',
    rock: 'bg-amber-800 text-white',
    ghost: 'bg-purple-700 text-white',
    dragon: 'bg-violet-600 text-white',
    dark: 'bg-gray-800 text-white',
    steel: 'bg-gray-500 text-white',
    fairy: 'bg-pink-300 text-gray-800',
  };